// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrecord"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionRecordCreate is the builder for creating a SubscriptionRecord entity.
type SubscriptionRecordCreate struct {
	config
	mutation *SubscriptionRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionRecordCreate) SetCreatedAt(v time.Time) *SubscriptionRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionRecordCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionRecordCreate) SetUpdatedAt(v time.Time) *SubscriptionRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionRecordCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionRecordCreate) SetUserID(v int64) *SubscriptionRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubscriptionRecordCreate) SetGroupID(v int64) *SubscriptionRecordCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionRecordCreate) SetSubscriptionID(v int64) *SubscriptionRecordCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_c *SubscriptionRecordCreate) SetNillableSubscriptionID(v *int64) *SubscriptionRecordCreate {
	if v != nil {
		_c.SetSubscriptionID(*v)
	}
	return _c
}

// SetPriceUsd sets the "price_usd" field.
func (_c *SubscriptionRecordCreate) SetPriceUsd(v float64) *SubscriptionRecordCreate {
	_c.mutation.SetPriceUsd(v)
	return _c
}

// SetNillablePriceUsd sets the "price_usd" field if the given value is not nil.
func (_c *SubscriptionRecordCreate) SetNillablePriceUsd(v *float64) *SubscriptionRecordCreate {
	if v != nil {
		_c.SetPriceUsd(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *SubscriptionRecordCreate) SetValidityDays(v int) *SubscriptionRecordCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *SubscriptionRecordCreate) SetNillableValidityDays(v *int) *SubscriptionRecordCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *SubscriptionRecordCreate) SetStartsAt(v time.Time) *SubscriptionRecordCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SubscriptionRecordCreate) SetExpiresAt(v time.Time) *SubscriptionRecordCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetAssignedBy sets the "assigned_by" field.
func (_c *SubscriptionRecordCreate) SetAssignedBy(v int64) *SubscriptionRecordCreate {
	_c.mutation.SetAssignedBy(v)
	return _c
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_c *SubscriptionRecordCreate) SetNillableAssignedBy(v *int64) *SubscriptionRecordCreate {
	if v != nil {
		_c.SetAssignedBy(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *SubscriptionRecordCreate) SetAssignedAt(v time.Time) *SubscriptionRecordCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *SubscriptionRecordCreate) SetNotes(v string) *SubscriptionRecordCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *SubscriptionRecordCreate) SetNillableNotes(v *string) *SubscriptionRecordCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SubscriptionRecordCreate) SetUser(v *User) *SubscriptionRecordCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *SubscriptionRecordCreate) SetGroup(v *Group) *SubscriptionRecordCreate {
	return _c.SetGroupID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_c *SubscriptionRecordCreate) SetSubscription(v *UserSubscription) *SubscriptionRecordCreate {
	return _c.SetSubscriptionID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_c *SubscriptionRecordCreate) SetAssignedByUserID(id int64) *SubscriptionRecordCreate {
	_c.mutation.SetAssignedByUserID(id)
	return _c
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *SubscriptionRecordCreate) SetNillableAssignedByUserID(id *int64) *SubscriptionRecordCreate {
	if id != nil {
		_c = _c.SetAssignedByUserID(*id)
	}
	return _c
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_c *SubscriptionRecordCreate) SetAssignedByUser(v *User) *SubscriptionRecordCreate {
	return _c.SetAssignedByUserID(v.ID)
}

// Mutation returns the SubscriptionRecordMutation object of the builder.
func (_c *SubscriptionRecordCreate) Mutation() *SubscriptionRecordMutation {
	return _c.mutation
}

// Save creates the SubscriptionRecord in the database.
func (_c *SubscriptionRecordCreate) Save(ctx context.Context) (*SubscriptionRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionRecordCreate) SaveX(ctx context.Context) *SubscriptionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PriceUsd(); !ok {
		v := subscriptionrecord.DefaultPriceUsd
		_c.mutation.SetPriceUsd(v)
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := subscriptionrecord.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionRecordCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionRecord.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SubscriptionRecord.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubscriptionRecord.group_id"`)}
	}
	if _, ok := _c.mutation.PriceUsd(); !ok {
		return &ValidationError{Name: "price_usd", err: errors.New(`ent: missing required field "SubscriptionRecord.price_usd"`)}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "SubscriptionRecord.validity_days"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "SubscriptionRecord.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "SubscriptionRecord.expires_at"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "SubscriptionRecord.assigned_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SubscriptionRecord.user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "SubscriptionRecord.group"`)}
	}
	return nil
}

func (_c *SubscriptionRecordCreate) sqlSave(ctx context.Context) (*SubscriptionRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionRecordCreate) createSpec() (*SubscriptionRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionrecord.Table, sqlgraph.NewFieldSpec(subscriptionrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PriceUsd(); ok {
		_spec.SetField(subscriptionrecord.FieldPriceUsd, field.TypeFloat64, value)
		_node.PriceUsd = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionrecord.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionrecord.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionrecord.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(subscriptionrecord.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(subscriptionrecord.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.UserTable,
			Columns: []string{subscriptionrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.GroupTable,
			Columns: []string{subscriptionrecord.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.SubscriptionTable,
			Columns: []string{subscriptionrecord.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.AssignedByUserTable,
			Columns: []string{subscriptionrecord.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssignedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionRecord.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionRecordCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionRecordUpsertOne {
	_c.conflict = opts
	return &SubscriptionRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionRecordCreate) OnConflictColumns(columns ...string) *SubscriptionRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionRecordUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionRecordUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionRecord node.
	SubscriptionRecordUpsertOne struct {
		create *SubscriptionRecordCreate
	}

	// SubscriptionRecordUpsert is the "OnConflict" setter.
	SubscriptionRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionRecordUpsert) SetUpdatedAt(v time.Time) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdateUpdatedAt() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionRecordUpsert) SetUserID(v int64) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdateUserID() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionRecordUpsert) SetGroupID(v int64) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdateGroupID() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldGroupID)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionRecordUpsert) SetSubscriptionID(v int64) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdateSubscriptionID() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldSubscriptionID)
	return u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *SubscriptionRecordUpsert) ClearSubscriptionID() *SubscriptionRecordUpsert {
	u.SetNull(subscriptionrecord.FieldSubscriptionID)
	return u
}

// SetPriceUsd sets the "price_usd" field.
func (u *SubscriptionRecordUpsert) SetPriceUsd(v float64) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldPriceUsd, v)
	return u
}

// UpdatePriceUsd sets the "price_usd" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdatePriceUsd() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldPriceUsd)
	return u
}

// AddPriceUsd adds v to the "price_usd" field.
func (u *SubscriptionRecordUpsert) AddPriceUsd(v float64) *SubscriptionRecordUpsert {
	u.Add(subscriptionrecord.FieldPriceUsd, v)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *SubscriptionRecordUpsert) SetValidityDays(v int) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdateValidityDays() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *SubscriptionRecordUpsert) AddValidityDays(v int) *SubscriptionRecordUpsert {
	u.Add(subscriptionrecord.FieldValidityDays, v)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *SubscriptionRecordUpsert) SetStartsAt(v time.Time) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdateStartsAt() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionRecordUpsert) SetExpiresAt(v time.Time) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdateExpiresAt() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldExpiresAt)
	return u
}

// SetAssignedBy sets the "assigned_by" field.
func (u *SubscriptionRecordUpsert) SetAssignedBy(v int64) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldAssignedBy, v)
	return u
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdateAssignedBy() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldAssignedBy)
	return u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *SubscriptionRecordUpsert) ClearAssignedBy() *SubscriptionRecordUpsert {
	u.SetNull(subscriptionrecord.FieldAssignedBy)
	return u
}

// SetAssignedAt sets the "assigned_at" field.
func (u *SubscriptionRecordUpsert) SetAssignedAt(v time.Time) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldAssignedAt, v)
	return u
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdateAssignedAt() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldAssignedAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *SubscriptionRecordUpsert) SetNotes(v string) *SubscriptionRecordUpsert {
	u.Set(subscriptionrecord.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionRecordUpsert) UpdateNotes() *SubscriptionRecordUpsert {
	u.SetExcluded(subscriptionrecord.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionRecordUpsert) ClearNotes() *SubscriptionRecordUpsert {
	u.SetNull(subscriptionrecord.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionRecordUpsertOne) UpdateNewValues() *SubscriptionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionRecordUpsertOne) Ignore() *SubscriptionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionRecordUpsertOne) DoNothing() *SubscriptionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionRecordCreate.OnConflict
// documentation for more info.
func (u *SubscriptionRecordUpsertOne) Update(set func(*SubscriptionRecordUpsert)) *SubscriptionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionRecordUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdateUpdatedAt() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionRecordUpsertOne) SetUserID(v int64) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdateUserID() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionRecordUpsertOne) SetGroupID(v int64) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdateGroupID() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateGroupID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionRecordUpsertOne) SetSubscriptionID(v int64) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdateSubscriptionID() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *SubscriptionRecordUpsertOne) ClearSubscriptionID() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetPriceUsd sets the "price_usd" field.
func (u *SubscriptionRecordUpsertOne) SetPriceUsd(v float64) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetPriceUsd(v)
	})
}

// AddPriceUsd adds v to the "price_usd" field.
func (u *SubscriptionRecordUpsertOne) AddPriceUsd(v float64) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.AddPriceUsd(v)
	})
}

// UpdatePriceUsd sets the "price_usd" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdatePriceUsd() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdatePriceUsd()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *SubscriptionRecordUpsertOne) SetValidityDays(v int) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *SubscriptionRecordUpsertOne) AddValidityDays(v int) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdateValidityDays() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateValidityDays()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *SubscriptionRecordUpsertOne) SetStartsAt(v time.Time) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdateStartsAt() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionRecordUpsertOne) SetExpiresAt(v time.Time) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdateExpiresAt() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *SubscriptionRecordUpsertOne) SetAssignedBy(v int64) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdateAssignedBy() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *SubscriptionRecordUpsertOne) ClearAssignedBy() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.ClearAssignedBy()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *SubscriptionRecordUpsertOne) SetAssignedAt(v time.Time) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdateAssignedAt() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *SubscriptionRecordUpsertOne) SetNotes(v string) *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertOne) UpdateNotes() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionRecordUpsertOne) ClearNotes() *SubscriptionRecordUpsertOne {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *SubscriptionRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionRecordCreateBulk is the builder for creating many SubscriptionRecord entities in bulk.
type SubscriptionRecordCreateBulk struct {
	config
	err      error
	builders []*SubscriptionRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionRecord entities in the database.
func (_c *SubscriptionRecordCreateBulk) Save(ctx context.Context) ([]*SubscriptionRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionRecordCreateBulk) SaveX(ctx context.Context) []*SubscriptionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionRecordUpsertBulk {
	_c.conflict = opts
	return &SubscriptionRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionRecordCreateBulk) OnConflictColumns(columns ...string) *SubscriptionRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionRecordUpsertBulk{
		create: _c,
	}
}

// SubscriptionRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionRecord nodes.
type SubscriptionRecordUpsertBulk struct {
	create *SubscriptionRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionRecordUpsertBulk) UpdateNewValues() *SubscriptionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionRecordUpsertBulk) Ignore() *SubscriptionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionRecordUpsertBulk) DoNothing() *SubscriptionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionRecordCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionRecordUpsertBulk) Update(set func(*SubscriptionRecordUpsert)) *SubscriptionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionRecordUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdateUpdatedAt() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionRecordUpsertBulk) SetUserID(v int64) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdateUserID() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionRecordUpsertBulk) SetGroupID(v int64) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdateGroupID() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateGroupID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionRecordUpsertBulk) SetSubscriptionID(v int64) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdateSubscriptionID() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *SubscriptionRecordUpsertBulk) ClearSubscriptionID() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetPriceUsd sets the "price_usd" field.
func (u *SubscriptionRecordUpsertBulk) SetPriceUsd(v float64) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetPriceUsd(v)
	})
}

// AddPriceUsd adds v to the "price_usd" field.
func (u *SubscriptionRecordUpsertBulk) AddPriceUsd(v float64) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.AddPriceUsd(v)
	})
}

// UpdatePriceUsd sets the "price_usd" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdatePriceUsd() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdatePriceUsd()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *SubscriptionRecordUpsertBulk) SetValidityDays(v int) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *SubscriptionRecordUpsertBulk) AddValidityDays(v int) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdateValidityDays() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateValidityDays()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *SubscriptionRecordUpsertBulk) SetStartsAt(v time.Time) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdateStartsAt() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionRecordUpsertBulk) SetExpiresAt(v time.Time) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdateExpiresAt() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *SubscriptionRecordUpsertBulk) SetAssignedBy(v int64) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdateAssignedBy() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *SubscriptionRecordUpsertBulk) ClearAssignedBy() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.ClearAssignedBy()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *SubscriptionRecordUpsertBulk) SetAssignedAt(v time.Time) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdateAssignedAt() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *SubscriptionRecordUpsertBulk) SetNotes(v string) *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionRecordUpsertBulk) UpdateNotes() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionRecordUpsertBulk) ClearNotes() *SubscriptionRecordUpsertBulk {
	return u.Update(func(s *SubscriptionRecordUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *SubscriptionRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
