// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrecord"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionRecordUpdate is the builder for updating SubscriptionRecord entities.
type SubscriptionRecordUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionRecordMutation
}

// Where appends a list predicates to the SubscriptionRecordUpdate builder.
func (_u *SubscriptionRecordUpdate) Where(ps ...predicate.SubscriptionRecord) *SubscriptionRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionRecordUpdate) SetUpdatedAt(v time.Time) *SubscriptionRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionRecordUpdate) SetUserID(v int64) *SubscriptionRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableUserID(v *int64) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionRecordUpdate) SetGroupID(v int64) *SubscriptionRecordUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableGroupID(v *int64) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionRecordUpdate) SetSubscriptionID(v int64) *SubscriptionRecordUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *SubscriptionRecordUpdate) ClearSubscriptionID() *SubscriptionRecordUpdate {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetOperation sets the "operation" field.
func (_u *SubscriptionRecordUpdate) SetOperation(v string) *SubscriptionRecordUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableOperation(v *string) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetPriceUsd sets the "price_usd" field.
func (_u *SubscriptionRecordUpdate) SetPriceUsd(v float64) *SubscriptionRecordUpdate {
	_u.mutation.ResetPriceUsd()
	_u.mutation.SetPriceUsd(v)
	return _u
}

// SetNillablePriceUsd sets the "price_usd" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillablePriceUsd(v *float64) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetPriceUsd(*v)
	}
	return _u
}

// AddPriceUsd adds value to the "price_usd" field.
func (_u *SubscriptionRecordUpdate) AddPriceUsd(v float64) *SubscriptionRecordUpdate {
	_u.mutation.AddPriceUsd(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *SubscriptionRecordUpdate) SetValidityDays(v int) *SubscriptionRecordUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableValidityDays(v *int) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *SubscriptionRecordUpdate) AddValidityDays(v int) *SubscriptionRecordUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *SubscriptionRecordUpdate) SetStartsAt(v time.Time) *SubscriptionRecordUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableStartsAt(v *time.Time) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionRecordUpdate) SetExpiresAt(v time.Time) *SubscriptionRecordUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableExpiresAt(v *time.Time) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *SubscriptionRecordUpdate) SetAssignedBy(v int64) *SubscriptionRecordUpdate {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableAssignedBy(v *int64) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *SubscriptionRecordUpdate) ClearAssignedBy() *SubscriptionRecordUpdate {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *SubscriptionRecordUpdate) SetAssignedAt(v time.Time) *SubscriptionRecordUpdate {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableAssignedAt(v *time.Time) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubscriptionRecordUpdate) SetNotes(v string) *SubscriptionRecordUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableNotes(v *string) *SubscriptionRecordUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SubscriptionRecordUpdate) ClearNotes() *SubscriptionRecordUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionRecordUpdate) SetUser(v *User) *SubscriptionRecordUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionRecordUpdate) SetGroup(v *Group) *SubscriptionRecordUpdate {
	return _u.SetGroupID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionRecordUpdate) SetSubscription(v *UserSubscription) *SubscriptionRecordUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_u *SubscriptionRecordUpdate) SetAssignedByUserID(id int64) *SubscriptionRecordUpdate {
	_u.mutation.SetAssignedByUserID(id)
	return _u
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *SubscriptionRecordUpdate) SetNillableAssignedByUserID(id *int64) *SubscriptionRecordUpdate {
	if id != nil {
		_u = _u.SetAssignedByUserID(*id)
	}
	return _u
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_u *SubscriptionRecordUpdate) SetAssignedByUser(v *User) *SubscriptionRecordUpdate {
	return _u.SetAssignedByUserID(v.ID)
}

// Mutation returns the SubscriptionRecordMutation object of the builder.
func (_u *SubscriptionRecordUpdate) Mutation() *SubscriptionRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionRecordUpdate) ClearUser() *SubscriptionRecordUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionRecordUpdate) ClearGroup() *SubscriptionRecordUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionRecordUpdate) ClearSubscription() *SubscriptionRecordUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearAssignedByUser clears the "assigned_by_user" edge to the User entity.
func (_u *SubscriptionRecordUpdate) ClearAssignedByUser() *SubscriptionRecordUpdate {
	_u.mutation.ClearAssignedByUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionRecordUpdate) check() error {
	if v, ok := _u.mutation.Operation(); ok {
		if err := subscriptionrecord.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "SubscriptionRecord.operation": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionRecord.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionRecord.group"`)
	}
	return nil
}

func (_u *SubscriptionRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionrecord.Table, subscriptionrecord.Columns, sqlgraph.NewFieldSpec(subscriptionrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(subscriptionrecord.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceUsd(); ok {
		_spec.SetField(subscriptionrecord.FieldPriceUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPriceUsd(); ok {
		_spec.AddField(subscriptionrecord.FieldPriceUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionrecord.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(subscriptionrecord.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionrecord.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionrecord.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(subscriptionrecord.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(subscriptionrecord.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(subscriptionrecord.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.UserTable,
			Columns: []string{subscriptionrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.UserTable,
			Columns: []string{subscriptionrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.GroupTable,
			Columns: []string{subscriptionrecord.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.GroupTable,
			Columns: []string{subscriptionrecord.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.SubscriptionTable,
			Columns: []string{subscriptionrecord.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.SubscriptionTable,
			Columns: []string{subscriptionrecord.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.AssignedByUserTable,
			Columns: []string{subscriptionrecord.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.AssignedByUserTable,
			Columns: []string{subscriptionrecord.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionRecordUpdateOne is the builder for updating a single SubscriptionRecord entity.
type SubscriptionRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionRecordMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionRecordUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionRecordUpdateOne) SetUserID(v int64) *SubscriptionRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableUserID(v *int64) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionRecordUpdateOne) SetGroupID(v int64) *SubscriptionRecordUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableGroupID(v *int64) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionRecordUpdateOne) SetSubscriptionID(v int64) *SubscriptionRecordUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *SubscriptionRecordUpdateOne) ClearSubscriptionID() *SubscriptionRecordUpdateOne {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetOperation sets the "operation" field.
func (_u *SubscriptionRecordUpdateOne) SetOperation(v string) *SubscriptionRecordUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableOperation(v *string) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetPriceUsd sets the "price_usd" field.
func (_u *SubscriptionRecordUpdateOne) SetPriceUsd(v float64) *SubscriptionRecordUpdateOne {
	_u.mutation.ResetPriceUsd()
	_u.mutation.SetPriceUsd(v)
	return _u
}

// SetNillablePriceUsd sets the "price_usd" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillablePriceUsd(v *float64) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetPriceUsd(*v)
	}
	return _u
}

// AddPriceUsd adds value to the "price_usd" field.
func (_u *SubscriptionRecordUpdateOne) AddPriceUsd(v float64) *SubscriptionRecordUpdateOne {
	_u.mutation.AddPriceUsd(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *SubscriptionRecordUpdateOne) SetValidityDays(v int) *SubscriptionRecordUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableValidityDays(v *int) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *SubscriptionRecordUpdateOne) AddValidityDays(v int) *SubscriptionRecordUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *SubscriptionRecordUpdateOne) SetStartsAt(v time.Time) *SubscriptionRecordUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableStartsAt(v *time.Time) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionRecordUpdateOne) SetExpiresAt(v time.Time) *SubscriptionRecordUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableExpiresAt(v *time.Time) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *SubscriptionRecordUpdateOne) SetAssignedBy(v int64) *SubscriptionRecordUpdateOne {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableAssignedBy(v *int64) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *SubscriptionRecordUpdateOne) ClearAssignedBy() *SubscriptionRecordUpdateOne {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *SubscriptionRecordUpdateOne) SetAssignedAt(v time.Time) *SubscriptionRecordUpdateOne {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableAssignedAt(v *time.Time) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubscriptionRecordUpdateOne) SetNotes(v string) *SubscriptionRecordUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableNotes(v *string) *SubscriptionRecordUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SubscriptionRecordUpdateOne) ClearNotes() *SubscriptionRecordUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionRecordUpdateOne) SetUser(v *User) *SubscriptionRecordUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionRecordUpdateOne) SetGroup(v *Group) *SubscriptionRecordUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionRecordUpdateOne) SetSubscription(v *UserSubscription) *SubscriptionRecordUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_u *SubscriptionRecordUpdateOne) SetAssignedByUserID(id int64) *SubscriptionRecordUpdateOne {
	_u.mutation.SetAssignedByUserID(id)
	return _u
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *SubscriptionRecordUpdateOne) SetNillableAssignedByUserID(id *int64) *SubscriptionRecordUpdateOne {
	if id != nil {
		_u = _u.SetAssignedByUserID(*id)
	}
	return _u
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_u *SubscriptionRecordUpdateOne) SetAssignedByUser(v *User) *SubscriptionRecordUpdateOne {
	return _u.SetAssignedByUserID(v.ID)
}

// Mutation returns the SubscriptionRecordMutation object of the builder.
func (_u *SubscriptionRecordUpdateOne) Mutation() *SubscriptionRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionRecordUpdateOne) ClearUser() *SubscriptionRecordUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionRecordUpdateOne) ClearGroup() *SubscriptionRecordUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionRecordUpdateOne) ClearSubscription() *SubscriptionRecordUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearAssignedByUser clears the "assigned_by_user" edge to the User entity.
func (_u *SubscriptionRecordUpdateOne) ClearAssignedByUser() *SubscriptionRecordUpdateOne {
	_u.mutation.ClearAssignedByUser()
	return _u
}

// Where appends a list predicates to the SubscriptionRecordUpdate builder.
func (_u *SubscriptionRecordUpdateOne) Where(ps ...predicate.SubscriptionRecord) *SubscriptionRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionRecordUpdateOne) Select(field string, fields ...string) *SubscriptionRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionRecord entity.
func (_u *SubscriptionRecordUpdateOne) Save(ctx context.Context) (*SubscriptionRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionRecordUpdateOne) SaveX(ctx context.Context) *SubscriptionRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionRecordUpdateOne) check() error {
	if v, ok := _u.mutation.Operation(); ok {
		if err := subscriptionrecord.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "SubscriptionRecord.operation": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionRecord.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionRecord.group"`)
	}
	return nil
}

func (_u *SubscriptionRecordUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionrecord.Table, subscriptionrecord.Columns, sqlgraph.NewFieldSpec(subscriptionrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionrecord.FieldID)
		for _, f := range fields {
			if !subscriptionrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(subscriptionrecord.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceUsd(); ok {
		_spec.SetField(subscriptionrecord.FieldPriceUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPriceUsd(); ok {
		_spec.AddField(subscriptionrecord.FieldPriceUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionrecord.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(subscriptionrecord.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionrecord.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionrecord.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(subscriptionrecord.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(subscriptionrecord.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(subscriptionrecord.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.UserTable,
			Columns: []string{subscriptionrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.UserTable,
			Columns: []string{subscriptionrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.GroupTable,
			Columns: []string{subscriptionrecord.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.GroupTable,
			Columns: []string{subscriptionrecord.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.SubscriptionTable,
			Columns: []string{subscriptionrecord.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.SubscriptionTable,
			Columns: []string{subscriptionrecord.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.AssignedByUserTable,
			Columns: []string{subscriptionrecord.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionrecord.AssignedByUserTable,
			Columns: []string{subscriptionrecord.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
